app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, SubmitField, TextAreaField, SelectField, FloatField, IntegerField
from wtforms.validators import DataRequired


class ProductForm(FlaskForm):
    name = StringField('Product Name', validators =[DataRequired()])
    category = SelectField('Choose your category', validators = [DataRequired()], 
        choices=[('1', 'None'), ('2', 'Picture'), ('3', 'Document'), ('4', 'Audio')])
    brand = StringField("Brand Name")
    quantity = IntegerField("Quantity", validators = [DataRequired()])
    price = FloatField("Price per unit", validators =[DataRequired()])
    describe = TextAreaField('Brief Description')
    image = FileField("Upload Picture1", validators = [FileRequired(), FileAllowed(['jpeg', 'png','jpg', 'jfif'])])
    submit = SubmitField("Add")


class OrderForm(FlaskForm):
    name = StringField('Name', validators =[DataRequired()])
    quantity = SelectField('Choose your category', validators = [DataRequired()], 
        choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])
    mobile = IntegerField("Quantity", validators = [DataRequired()])
    submit = SubmitField("Order Now")


class CheckOutForm(FlaskForm):
    customer = StringField('Customer', validators =[DataRequired()])
    product = StringField('The Product')
    supplier = StringField('The Supplier')
    quantity = IntegerField("Quantity", validators = [DataRequired()])
    price = FloatField("Price per unit", validators =[DataRequired()])
    submit = SubmitField("Order")

app/main/routes.py
from flask import Blueprint, render_template, flash, redirect,url_for, request
from app.main.forms import ProductForm, CheckOutForm
from app.auth.forms import LoginForm
from app.models import Product, User, Cart
from flask_login import login_required, current_user
from app import photos
from app import db
import secrets

main = Blueprint("main", __name__)

"""
@main.route('/home')
@main.route('/')
def home():
	products = Product.query.all()
	return render_template('main/index.html', products = products)
"""
@main.route('/', methods = ["GET", "POST"])
@main.route('/home', methods = ["GET", "POST"])
def home():
	products = Product.query.order_by(Product.date.desc()).all()
	#products = Product.query.all()
	return render_template('main/home.html', products = products)


@main.route("/addproduct", methods = ["GET", "POST"])
@login_required
def addproduct():
	form = ProductForm()
	if form.validate_on_submit():
		name = form.name.data
		category = form.category.data
		brand = form.brand.data
		quantity = form.quantity.data
		price = form.price.data
		describe = form.describe.data
		image = photos.save(request.files.get('image'), name = secrets.token_hex(10) + ".")
		#image = form.image.data

		product = Product(name = name, category = category, brand = brand, quantity = quantity, price = price,
			description=describe, image = image, supplier = current_user)
		db.session.add(product)
		db.session.commit()
		flash('Your product has been added', 'success')
		return redirect(url_for('main.home'))
	return render_template('main/addproduct.html', form=form, legend = "ADD PRODUCTS")

@main.route("/account/<string:username>")
def account(username):
    user = User.query.filter_by(username=username).first_or_404()
    products = Product.query.filter_by(supplier=user)
    #image_file = url_for('static', filename = 'img/' + user.image_file)
    return render_template('main/account.html', user = user, products = products, title = user.name)

@main.route("/productdetails/<int:id>")
def productdetails(id):
	product = Product.query.get_or_404(id)
	return render_template('main/productdetails.html', product = product, id = product.id)

@main.route("/cart", methods = ["GET", "POST"])
def cart():
	product_id = request.form.get("product_id")
	#if product_id:
	product = Product.query.get_or_404(product_id)
	print(product)
	cart = Cart(carter = current_user, cart_product = product)
	db.session.add(cart)
	db.session.commit()
	flash("This product has been added to your cart", "success")
	return redirect(url_for('main.display_cart'))

@main.route("/user/display_cart")
def display_cart():
	carts = Cart.query.filter_by(customer_id = current_user.id)
	total = carts.count()
	return render_template('main/cart.html', carts = carts, total= total)

@main.route("/user/checkout", methods = ["GET", "POST"])
def checkout():
	form = CheckOutForm()
	product_id = request.form.get("product_id")
	#print(product_id)
	return render_template('main/checkout.html', product_id = product_id, form = form)

@main.route('/deletecat/<int:id>', methods=['GET','POST'])
def deletecat(id):
    cart = Cart.query.get_or_404(id)
    if request.method=="POST":
        db.session.delete(cart)
        flash(f"The brand {cart.cart_product.name} was deleted from your database","success")
        db.session.commit()
        return redirect(url_for('main.display_cart'))
    flash(f"The brand {cart.cart_product.name} can't be  deleted from your database","warning")
    return redirect(url_for('main.display_cart'))

app/templates/main/account.html
<!DOCTYPE html>
<html>
<head>
  <title>{{title}}</title>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<meta http-equiv="refresh" content="5; url=http://localhost:5000/account">
-->
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <div class="content-section">
   <div class="media">
     <div class="media-body">
       <h2 class="account-heading">{{user.username}}</h2>
       <p class="text-secondary">{{user.email}}</p>
       <p><span style="font-weight: bold;">About me:</span></p>
       <p class="text-secondary">{{user.name}}</p>
     </div>
   </div>
 </div>
 <div>
   <legend><h3>Posts</h3></legend>
   <hr>
    
    <div class="row">
      {% for product in products %}
       <div class="col">
        <a href="{{url_for('main.productdetails', id = product.id)}}">
          <p>{{product.name}}</p>
        </a>
        <a href="{{url_for('main.productdetails', id = product.id)}}">
          <img src="{{url_for('static', filename = 'images/' + product.image)}}" width="150" 
    height="200" style="background: white; width: 100%">
        </a>
      </div>
       {% endfor %}
              
    </div>
 <!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>
    
   

app/templates/main/addproduct.html
<div class="row">
	<div class="col-3"></div>
	<div class="col-6">

<form class="jumbotron" action="" method="POST" enctype="multipart/form-data">
  {{form.hidden_tag()}}
  <fieldset class="form-group">
    <legend class="border-bottom mb-4 text-center">{{legend}}</legend>
        <div class="form-group">
            {{form.name.label(class = 'form-control-label')}}
            {% if form.name.errors %}
                {{form.name(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.name.errors%}
                  <span>{{error}}</span>
                {% endfor %}
              </div>
            {% else %}
              {{form.name(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>
        <div class="form-group">
            {{form.category.label(class = 'form-control-label')}}
            {% if form.category.errors %}
                {{form.category(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.category.errors %}
                  <span>{{error}}</span>
                {%endfor%}
              </div>
            {% else %}
              {{form.category(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>

         <div class="form-group">
            {{form.brand.label(class = 'form-control-label')}}
            {% if form.brand.errors %}
                {{form.brand(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.brand.errors %}
                  <span>{{error}}</span>
                {%endfor%}
              </div>
            {% else %}
              {{form.brand(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>

         <div class="form-group">
            {{form.quantity.label(class = 'form-control-label')}}
            {% if form.quantity.errors %}
                {{form.quantity(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.quantity.errors %}
                  <span>{{error}}</span>
                {%endfor%}
              </div>
            {% else %}
              {{form.quantity(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>

        <div class="form-group">
            {{form.price.label(class = 'form-control-label')}}
            {% if form.price.errors %}
                {{form.price(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.price.errors %}
                  <span>{{error}}</span>
                {%endfor%}
              </div>
            {% else %}
              {{form.price(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>

         <div class="form-group">
            {{form.describe.label(class = 'form-control-label')}}
            {% if form.describe.errors %}
                {{form.describe(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.describe.errors %}
                  <span>{{error}}</span>
                {%endfor%}
              </div>
            {% else %}
              {{form.describe(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>

        <div class="form-group">
            {{form.image.label()}}
            {{form.image(class = "form-control-file")}}

            {% if form.image.errors %}
              {%for error in form.image.errors %}
                <span class = 'text-danger'>{{error}}</span><br>
                {%endfor%}
            {% endif %}
        </div>

  </fieldset>

<div class="form-group">
 {{form.submit(class = "btn btn-outline-info")}}
</div>
</form>

	</div>
	<div class="col-3"></div>
</div>
  

app/templates/main/cart.html
<!DOCTYPE html>
<html>
<head>
	<title>Cart</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<meta http-equiv="refresh" content="5; url=http://localhost:5000/account">
-->
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

	<h1>This page shows all the carts of <span><strong>{{current_user.name}}({{total}})</strong></span></h1>
	<hr>
	<div>
		<!--
		{% for cart in carts %}
		<img src="{{url_for('static', filename = 'images/' + cart.cart_product.image)}}" width="150" 
		height="200" style="background: white; width:">
		<button>Delete</button>
		<p>{{cart.cart_product}}</p>
		{% endfor %}
		-->
		

	<table class="table tbale-sm">
        <thead>
            <th>Sr</th>
            <th>Image</th>
            <th>Name</th>
            <th>Price</th>
            <th>Brand</th>
            <th>Delete</th>
        </thead>
        <tbody>
          {% for cart in carts %}
          <tr>
            <td>{{loop.index}}</td>
            <td> <img src="{{url_for('static',filename='images/' + cart.cart_product.image)}}" alt="{{cart.cart_product.name}}" width="50" height="20"></td>
            <td>{{ cart.cart_product.name }}</td>
            <td>{{ cart.cart_product.price }}</td>
            <td>{{ cart.cart_product.brand}}</td>
            <td><button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal-{{cart.cart_product.id}}">
              Delete
            </button></td>
          </tr>

 <!--============= MODEL ===================-->
        <div class="modal fade" id="exampleModal-{{cart.cart_product.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{cart.cart_product.name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p class="text-danger">Are you Sure that you want to delete ({{ cart.cart_product.name }})</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <form action="{{url_for('main.deletecat', id = cart.id)}}" method="post">
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                
              </div>
            </div>
          </div>
        </div>
<!--==============MODEL ===================-->

          {% endfor %}
        </tbody>
    </table>
	</div>

 <!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

app/templates/main/checkout.html
<!DOCTYPE html>
<html>
<head>
	<title>Check Out</title>
		<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<meta http-equiv="refresh" content="5; url=http://localhost:5000/account">
-->
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
	<H1>THis is the CHeck Out Page</H1>
	<h2>Product ID: {{product_id}}</h2>
	<hr>
<div class="row">
	<div class="col"></div>
	<div class="col">
		
 <form class="jumbotron" action="" method="POST" enctype="multipart/form-data">
  {{form.hidden_tag()}}
  <fieldset class="form-group">
    <legend class="border-bottom mb-4 text-center">{{legend}}</legend>
        <div class="form-group">
            {{form.customer.label(class = 'form-control-label')}}
            {% if form.customer.errors %}
                {{form.customer(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.customer.errors%}
                  <span>{{error}}</span>
                {% endfor %}
              </div>
            {% else %}
              {{form.customer(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>
        <div class="form-group">
            {{form.product.label(class = 'form-control-label')}}
            {% if form.product.errors %}
                {{form.product(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.product.errors %}
                  <span>{{error}}</span>
                {%endfor%}
              </div>
            {% else %}
              {{form.product(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>

         <div class="form-group">
            {{form.supplier.label(class = 'form-control-label')}}
            {% if form.supplier.errors %}
                {{form.supplier(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.supplier.errors %}
                  <span>{{error}}</span>
                {%endfor%}
              </div>
            {% else %}
              {{form.supplier(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>

         <div class="form-group">
            {{form.quantity.label(class = 'form-control-label')}}
            {% if form.quantity.errors %}
                {{form.quantity(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.quantity.errors %}
                  <span>{{error}}</span>
                {%endfor%}
              </div>
            {% else %}
              {{form.quantity(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>

        <div class="form-group">
            {{form.price.label(class = 'form-control-label')}}
            {% if form.price.errors %}
                {{form.price(class = 'form-control form-control-sm is-invalid')}}
              <div class="invalid-feedback">
                {%for error in form.price.errors %}
                  <span>{{error}}</span>
                {%endfor%}
              </div>
            {% else %}
              {{form.price(class = 'form-control form-control-sm')}}
            {% endif %}
        </div>
  </fieldset>
  <div class="form-group">
 {{form.submit(class = "btn btn-outline-info")}}
</div>

</form>

	</div>
	<div class="col"></div>
</div>

 <!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

app/templates/main/home.html
<!doctype html>
<html lang="en">
  <head>
    <title>QuantiCom</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<meta http-equiv="refresh" content="5; url=http://localhost:5000/account">
-->
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style type="text/css">
        #main-bar {
          border: 2px solid black;
        }
    </style>
  </head>
  {% include "includes/_nav2.html"%}
  <body class = "container" style="background: black;">
    {% include "includes/_messages.html" %}
    <main id ="body">
        <div class="row">
            {% for product in products %}
              <div class="col-3 mr-auto mt-2">
                  {% include "includes/_products.html" %}
              </div>
            {% endfor %}
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <script type="text/javascript">
          window.onload = function (){
            
            let signin = document .querySelector("#signin");
            let account = document.querySelector("#account");
            let addproduct = document.querySelector("#addproduct");
            let register = document.querySelector("#register");
            let logout = document.querySelector("#logout");
            

            signin.onclick = function (){
              load_page("login");
              //return false;
            }

            register.onclick = function (){
              load_page("register");
              //return false;
            }


            addproduct.onclick = function (){
              load_page("addproduct");
              //return false;
            }

            logout.onclick = function (){
              load_page("logout");
              //return false;
            }

            account.onclick = function (){
              load_page("account");
              //return false;
            }

          }

          function load_page(route) {
                const request = new XMLHttpRequest();
                request.open('GET', `/${route}`);
                request.onload = () => {
                    const response = request.responseText;
                    document.querySelector('#body').innerHTML = response;
                };
                request.send();
              };
  
        </script>
  </body>
</html>

app/templates/main/index.html
{% extends 'base.html' %}
{% block body %}
    <div class="row">
    	{% for product in products %}
    	<div class="col-3">
    		<div class="items" style="border: 2px solid red; margin-top: 2%;">
	    		{% include "includes/_products.html"%}
	    	</div>
    	</div>
    	{% endfor %}
    </div>


{% endblock %}

app/templates/main/index2.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Mens Hut</title>



<script type="text/javascript">
function productsAjax (){
            request = new XMLHttpRequest();
            request.open("GET", "/addproducts", true);

            request.onload =function (){
                response = request.responseText;
                document.querySelector('body').innerHTML = response;
                return false;
            }
            
            request.send();
        
    }

   

        window.onload = function(){
        elem1 = document.querySelector("#addproduct");
        elem1.onclick = function () {
            productsAjax();
        }
    }
</script>
        <meta charset="utf-8">
        <link rel="icon" href="{{ url_for('static', filename='image/other/logo_icon.png') }}" type="image/x-icon">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    </head>
    <body style="background-image: url({{ url_for('static', filename='image/nice.jpg') }}); margin-top: 57px">
        {% include 'includes/_navbar.html' %}
        <div class="container">
            {% with messages = get_flashed_messages(with_categories = true)%}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{category}}">
                  {{message}}
                </div>
      
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"></script>
    </body>
    {% include 'includes/_footer.html' %}
</html>

app/templates/main/productdetails.html
<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<meta http-equiv="refresh" content="5; url=http://localhost:5000/account">
-->
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    <div class="container mt-5">
    <div class="row">
        <div class="col-md-6" id="b_image">
            <img src="{{url_for('static',filename='images/' + product.image)}}" alt="{{product.name}}" width="400" height="400">
        </div>
        <div class="col-md-6">
            <h1>Supplier: 
                <a href="{{url_for('main.account', username = product.supplier.username)}}">
                    {{product.supplier}}
                </a>
            </h1>

            <h4>Product name: {{product.name}} </h4>
            <hr>
            <p>Product price: ${{product.price}}</p>
            <hr>
            <b>Product discription</b>
            <p>{{product.description}}</p>
            <form action="" method="post">
                <input type="hidden" name="product_id" value="{{product.id}}">
                <button type="submit" class="btn btn-sm btn-warning">Check Out</button>
                <label for="quantity">Quantity: </label>
                <input type="number" name="quantity" value="1" min="1" max="{{product.quantity}}">
            </form>
        
            <form action="" method="post">
                <input type="hidden" name="product_id" value="{{product.id}}">
                <button type="submit" class="btn btn-sm btn-warning">Add to Cart</button>
                <label for="quantity">Quantity: </label>
                <input type="number" name="quantity" value="1" min="1" max="{{product.quantity}}">
            </form>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12" id="s_image">
            <img src="{{url_for('static',filename='images/'+ product.image)}}" alt="{{product.name}}" width="100" height="100">
        </div>
    </div>
   
</div>
 <!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script>
    /*
   var b_image = document.getElementById('b_image');
   var s_image = document.getElementById('s_image').getElementsByTagName('img');
    for(var i = 0; i < s_image.length; i++){

        s_image[i].addEventListener('click', full_image);
    }
    function full_image(){
        var ImageSRC = this.getAttribute('src');
        b_image.innerHTML = "<img src=" + ImageSRC + " width='400' height='400'>";
    }
    */
</script>
</body>
</html>