app/main/routes.py
from flask import Blueprint, render_template, flash, redirect,url_for, request
from app.main.forms import ProductForm, CheckOutForm
from app.auth.forms import LoginForm
from app.models import Product, User, Cart
from flask_login import login_required, current_user
from app import photos
from app import db
import secrets

main = Blueprint("main", __name__)

"""
@main.route('/home')
@main.route('/')
def home():
	products = Product.query.all()
	return render_template('main/index.html', products = products)
"""
@main.route('/', methods = ["GET", "POST"])
@main.route('/home', methods = ["GET", "POST"])
def home():
	products = Product.query.order_by(Product.date.desc()).all()
	#products = Product.query.all()
	return render_template('main/home.html', products = products)


@main.route("/addproduct", methods = ["GET", "POST"])
@login_required
def addproduct():
	form = ProductForm()
	if form.validate_on_submit():
		name = form.name.data
		category = form.category.data
		brand = form.brand.data
		quantity = form.quantity.data
		price = form.price.data
		describe = form.describe.data
		image = photos.save(request.files.get('image'), name = secrets.token_hex(10) + ".")
		#image = form.image.data

		product = Product(name = name, category = category, brand = brand, quantity = quantity, price = price,
			description=describe, image = image, supplier = current_user)
		db.session.add(product)
		db.session.commit()
		flash('Your product has been added', 'success')
		return redirect(url_for('main.home'))
	return render_template('main/addproduct.html', form=form, legend = "ADD PRODUCTS")

@main.route("/account/<string:username>")
def account(username):
    user = User.query.filter_by(username=username).first_or_404()
    products = Product.query.filter_by(supplier=user)
    #image_file = url_for('static', filename = 'img/' + user.image_file)
    return render_template('main/account.html', user = user, products = products, title = user.name)

@main.route("/productdetails/<int:id>")
def productdetails(id):
	product = Product.query.get_or_404(id)
	return render_template('main/productdetails.html', product = product, id = product.id)

@main.route("/cart", methods = ["GET", "POST"])
def cart():
	product_id = request.form.get("product_id")
	#if product_id:
	product = Product.query.get_or_404(product_id)
	print(product)
	cart = Cart(carter = current_user, cart_product = product)
	db.session.add(cart)
	db.session.commit()
	flash("This product has been added to your cart", "success")
	return redirect(url_for('main.display_cart'))

@main.route("/user/display_cart")
def display_cart():
	carts = Cart.query.filter_by(customer_id = current_user.id)
	total = carts.count()
	return render_template('main/cart.html', carts = carts, total= total)

@main.route("/user/checkout", methods = ["GET", "POST"])
def checkout():
	form = CheckOutForm()
	product_id = request.form.get("product_id")
	#print(product_id)
	return render_template('main/checkout.html', product_id = product_id, form = form)

@main.route('/deletecat/<int:id>', methods=['GET','POST'])
def deletecat(id):
    cart = Cart.query.get_or_404(id)
    if request.method=="POST":
        db.session.delete(cart)
        flash(f"The brand {cart.cart_product.name} was deleted from your database","success")
        db.session.commit()
        return redirect(url_for('main.display_cart'))
    flash(f"The brand {cart.cart_product.name} can't be  deleted from your database","warning")
    return redirect(url_for('main.display_cart'))

app/templates/includes/_footer.html
<!-- Footer -->
<section id="footer">
    <div class="container">
        <div class="row text-center text-xs-center text-sm-left text-md-left">
            <div class="col-xs-12 col-sm-4 col-md-4">
                <h5>Quick Links</h5>
                <ul class="list-unstyled quick-links">
                    <li><a href="/"><i class="fa fa-angle-double-right"></i>Home</a></li>
                    <li><a href="/tshirt"><i class="fa fa-angle-double-right"></i>T-Shirt</a></li>
                    <li><a href="/belt"><i class="fa fa-angle-double-right"></i>Belt</a></li>
                    <li><a href="/shoes"><i class="fa fa-angle-double-right"></i>Shoes</a></li>
                    <li><a href="/wallet"><i class="fa fa-angle-double-right"></i>Wallet</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4">
                <h5>Social</h5>
                <ul class="list-unstyled quick-links">
                    <li><a href=""><i class="fa fa-angle-double-right"></i>Facebook</a></li>
                    <li><a href=""><i class="fa fa-angle-double-right"></i>Youtube</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4">
                <h5>Who We Are</h5>
                <ul class="list-unstyled quick-links">
                    <li><a href=""><i class="fa fa-angle-double-right"></i>About</a></li>
                    <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
                    <li><a href=""><i class="fa fa-angle-double-right"></i>Developed by Mohsingram</a></li>
                    <li><a href="/developer"><i class="fa fa-angle-double-right"></i>Developer</a></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                <p class="h6"><a class="text-green ml-2" href="" target="">Mohsin Gram</a> &copy All
                    right Reversed.</p>
            </div>
        </div>
    </div>
</section>
<!-- ./Footer -->

app/templates/includes/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}</dt>
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    {% for error in field.errors %}
      <span class="help-inline">{{ error }}</span>
    {% endfor %}
  {% endif %}
{% endmacro %}

app/templates/includes/_messages.html
    {% with messages = get_flashed_messages(with_categories = true)%}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{category}}">
            {{message}}
          </div>

        {% endfor %}
      {% endif %}
    {% endwith %}

app/templates/includes/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark mb-2 mt-2" id="main-bar">
    <a class="navbar-brand text-warning" href="{{url_for('main.home')}}">QuantiCom</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
     <form action="/search" method="get" class="w-100 m-0" style="padding-right: 20%;">
                <div class="input-group-append rounded-left">
                    <input type="text" class="form-control rounded-left form-control-sm" autocomplete="off" style="float: left; border-radius: 0;" name="q" placeholder="What you want...">
                    <button class="btn btn-success btn-sm rounded-right" style="border-radius: 0;" type="submit">Search</button>
            </div>
    </form>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    
        <li class="nav-item text-info btn btn-danger ml-2" id="account" data-page = "account">{{current_user.username}}</li>
        <li class="nav-item text-info btn btn-danger ml-2" id="addproduct" data-page = "addproduct">Add Product</li>
        <li class="nav-item text-info btn btn-danger ml-2" id="logout" data-page = "Logout">Logout</li>
        
        <li class="nav-item text-info btn btn-danger ml-2" id="signin" data-page = "register">Login</li>
        <li class="nav-item text-info btn btn-danger ml-2" id="register" data-page = "register">Register</li>                 
  </ul>
</div>

</nav>

app/templates/includes/_nav1.html
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom shadow-sm">
    <a class="navbar-brand text-warning" href="/">QuantiCom</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <div class="input-group p-0 justify-content-center">
            <form action="/search" method="get" class="w-100 m-0" style="padding-right: 20%;">
                <div class="input-group-append rounded-left">
                    <input type="text" class="form-control rounded-left form-control-sm" autocomplete="off" style="float: left; border-radius: 0;" name="q" placeholder="What you want...">
                    <button class="btn btn-success btn-sm rounded-right" style="border-radius: 0;" type="submit">Search</button>
                </div>
            </form>
        </div>
        <ul class="navbar-nav ml-auto">
            {% if session.logged_in %}
            <li class="nav-item"><a href="/" class="nav-link text-danger">Home</a></li>
            <li class="nav-item"><a href="/profile?user={{session.uid}}" class="nav-link text-danger">Mohsin</a>
            </li>
            <li class="nav-item"><a href="/out" class="nav-link text-danger">Logout</a></li>
            {% else %}
            <li class="nav-item"><a href="/" class="nav-link text-danger">Home</a></li>
            <li class="nav-item"><a href="/register" class="nav-link text-danger">Signup</a></li>
            <li class="nav-item"><a href="/login" class="nav-link text-danger">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

app/templates/includes/_nav2.html
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <a class="navbar-brand text-warning" href="{{url_for('main.home')}}"><strong>QuantiCom</strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <form action="/search" method="get" class="w-100 m-0" style="padding-right: 20%;" >
                <div class="input-group-append rounded-left">
                    <input type="text" class="form-control rounded-left form-control-sm" autocomplete="off" style="float: left; border-radius: 0;" name="q" placeholder="What you want...">
                    <button class="btn btn-success btn-sm rounded-right" style="border-radius: 0;" type="submit">Search</button>
            </div>
  </form>
  <ul class="navbar-nav ml-auto">
      <li class="nav-item"><a href="{{url_for('main.account', username = current_user.username)}}" class="nav-link text-danger">{{current_user.name}}</a></li>
  </ul>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><strong>MENU</strong> 
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{url_for('auth.register')}}">Register</a>
          <a class="dropdown-item" href="{{url_for('auth.login')}}">Login</a>
          <a class="dropdown-item" href="{{url_for('main.display_cart')}}">Cart</a>
          <a class="dropdown-item" href="#">Others</a>
          <a class="dropdown-item" href="{{url_for('main.addproduct')}}">Add product</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/templates/includes/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom shadow-sm fixed-top">
    <a class="navbar-brand" href="{{url_for('main.index2')}}">Quanticom</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <div class="input-group p-0 justify-content-center">
            <form action="/search" method="get" class="w-100 m-0" style="padding-right: 20%;">
                <div class="input-group-append rounded-left">
                    <input type="text" class="form-control rounded-left form-control-sm" autocomplete="off" style="float: left; border-radius: 0;" name="q" placeholder="What you want...">
                    <button class="btn btn-success btn-sm rounded-right" style="border-radius: 0;" type="submit">Search</button>
                </div>
            </form>
        </div>
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <div class = "btn" id = "div1">Hi</div>
            <span class="btn" id="home">Home</span> 
            <li class="nav-item"><a href="{{url_for('main.account', username = current_user.username)}}" class="nav-link"><span class=""></span>{{current_user.name}}</a>
            </li>
            <span class="btn" id="addproduct">Add</span>
            </li>
            <li class="nav-item"><a href="{{url_for('auth.register')}}" class="nav-link"><span class=""></span> Logout</a></li>
            {% else %}
            <li class="nav-item"><a href="" class="nav-link"><span class=""></span> Home</a></li>
            <li class="nav-item"><a href="{{url_for('auth.register')}}" class="nav-link"><span class=""></span> Signup</a></li>
            <li class="nav-item"><a href="{{url_for('auth.login')}}" class="nav-link"><span class=""></span> Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

app/templates/includes/_products.html
<!--
<div>
	<p class="text-success">Product Name: {{product.name}}</p>
	<img src="{{url_for('static', filename = 'images/' + product.image)}}" width="150" 
	height="150" style="background: white;">
	<div class="btn btn-success mt-1" style="text-align: right;">Order</div>
</div>
<div class="card-img-top" style="background: url('static/images/{{product.image}}'); background-repeat:no-repeat; background-size: cover; height:200px;width:100% "></div>
<a href="" class="float-right btn btn-sm btn-primary">Add To Cart</a>
-->

<div class="card mb-auto mr-auto" style="border: 2px solid gold;">
	<a href="{{url_for('main.productdetails', id = product.id)}}" class="btn" style="border-bottom: 2px solid red;">
		<img src="{{url_for('static', filename = 'images/' + product.image)}}" width="150" 
		height="200" style="background: white; width: 100%">
	</a>
    <div class="card-body">
        <h5>
        <a class="card-title" href="{{url_for('main.productdetails', id = product.id)}}">
        	{{ product.name}}

        </a>
        <form action = "{{url_for('main.checkout')}}" method="POST">
				<input type="hidden" name="product_id" value="{{product.id}}">
				<input class="float btn btn-sm btn-success" type="submit" name="" value="Check Out">
		</form>

       	</h5>
        	
        <h4>
        	<form action = "{{url_for('main.cart')}}" method="POST">
				<input type="hidden" name="product_id" value="{{product.id}}">
				<input class="float-right btn btn-sm btn-primary" type="submit" name="" value="Add to Cart">
			</form>
        ${{product.price}}
        </h4>
        
    </div>
</div>